export const NAVIGATE_URL = 'NAVIGATE_URL';
export const CLICK = "CLICK";
export const INPUT = "INPUT";
export const HOVER = "HOVER";
export const SCROLL_TO_VIEW ="SCROLL_TO_VIEW";
export const ASSERT_TEXT="ASSERT_TEXT";
export const EXTRACT_INFO = "EXTRACT_INFO";
export const SCREENSHOT = "SCREENSHOT";
export const BLACKOUT = "BLACKOUT";
export const WAIT = "WAIT";
export const PAGE_SCREENSHOT = "PAGE_SCREENSHOT";
export const SET_DEVICE = 'SET_DEVICE';

export enum ACTIONS_IN_TEST {
    SET_DEVICE = "SET_DEVICE",
    NAVIGATE_URL = "NAVIGATE_URL",
    VALIDATE_SEO = "VALIDATE_SEO",
    CLICK = "CLICK",
    INPUT = "INPUT",
    HOVER = "HOVER",
    SCROLL_TO_VIEW = "SCROLL_TO_VIEW",
    ASSERT_ELEMENT = "ASSERT_ELEMENT",
    EXTRACT_INFO = "EXTRACT_INFO",
    ELEMENT_SCREENSHOT = "ELEMENT_SCREENSHOT",
    BLACKOUT = "BLACKOUT",
    WAIT = "WAIT",
    PAGE_SCREENSHOT = "PAGE_SCREENSHOT",
    CAPTURE_CONSOLE = "CAPTURE_CONSOLE"
};
